/*
Deployment script for RedeSocial

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "RedeSocial"
:setvar DefaultFilePrefix "RedeSocial"
:setvar DefaultDataPath "C:\Users\Joao\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\MSSQLLocalDB"
:setvar DefaultLogPath "C:\Users\Joao\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\MSSQLLocalDB"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [master];


GO

IF (DB_ID(N'$(DatabaseName)') IS NOT NULL) 
BEGIN
    ALTER DATABASE [$(DatabaseName)]
    SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE [$(DatabaseName)];
END

GO
PRINT N'Creating $(DatabaseName)...'
GO
CREATE DATABASE [$(DatabaseName)]
    ON 
    PRIMARY(NAME = [$(DatabaseName)], FILENAME = N'$(DefaultDataPath)$(DefaultFilePrefix)_Primary.mdf')
    LOG ON (NAME = [$(DatabaseName)_log], FILENAME = N'$(DefaultLogPath)$(DefaultFilePrefix)_Primary.ldf') COLLATE SQL_Latin1_General_CP1_CI_AS
GO
USE [$(DatabaseName)];


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET ANSI_NULLS ON,
                ANSI_PADDING ON,
                ANSI_WARNINGS ON,
                ARITHABORT ON,
                CONCAT_NULL_YIELDS_NULL ON,
                NUMERIC_ROUNDABORT OFF,
                QUOTED_IDENTIFIER ON,
                ANSI_NULL_DEFAULT ON,
                CURSOR_DEFAULT LOCAL,
                CURSOR_CLOSE_ON_COMMIT OFF,
                AUTO_CREATE_STATISTICS ON,
                AUTO_SHRINK OFF,
                AUTO_UPDATE_STATISTICS ON,
                RECURSIVE_TRIGGERS OFF 
            WITH ROLLBACK IMMEDIATE;
        ALTER DATABASE [$(DatabaseName)]
            SET AUTO_CLOSE OFF 
            WITH ROLLBACK IMMEDIATE;
    END


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET ALLOW_SNAPSHOT_ISOLATION OFF;
    END


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET READ_COMMITTED_SNAPSHOT OFF 
            WITH ROLLBACK IMMEDIATE;
    END


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET AUTO_UPDATE_STATISTICS_ASYNC OFF,
                PAGE_VERIFY NONE,
                DATE_CORRELATION_OPTIMIZATION OFF,
                DISABLE_BROKER,
                PARAMETERIZATION SIMPLE,
                SUPPLEMENTAL_LOGGING OFF 
            WITH ROLLBACK IMMEDIATE;
    END


GO
IF IS_SRVROLEMEMBER(N'sysadmin') = 1
    BEGIN
        IF EXISTS (SELECT 1
                   FROM   [master].[dbo].[sysdatabases]
                   WHERE  [name] = N'$(DatabaseName)')
            BEGIN
                EXECUTE sp_executesql N'ALTER DATABASE [$(DatabaseName)]
    SET TRUSTWORTHY OFF,
        DB_CHAINING OFF 
    WITH ROLLBACK IMMEDIATE';
            END
    END
ELSE
    BEGIN
        PRINT N'The database settings cannot be modified. You must be a SysAdmin to apply these settings.';
    END


GO
IF IS_SRVROLEMEMBER(N'sysadmin') = 1
    BEGIN
        IF EXISTS (SELECT 1
                   FROM   [master].[dbo].[sysdatabases]
                   WHERE  [name] = N'$(DatabaseName)')
            BEGIN
                EXECUTE sp_executesql N'ALTER DATABASE [$(DatabaseName)]
    SET HONOR_BROKER_PRIORITY OFF 
    WITH ROLLBACK IMMEDIATE';
            END
    END
ELSE
    BEGIN
        PRINT N'The database settings cannot be modified. You must be a SysAdmin to apply these settings.';
    END


GO
ALTER DATABASE [$(DatabaseName)]
    SET TARGET_RECOVERY_TIME = 0 SECONDS 
    WITH ROLLBACK IMMEDIATE;


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET FILESTREAM(NON_TRANSACTED_ACCESS = OFF),
                CONTAINMENT = NONE 
            WITH ROLLBACK IMMEDIATE;
    END


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET AUTO_CREATE_STATISTICS ON(INCREMENTAL = OFF),
                MEMORY_OPTIMIZED_ELEVATE_TO_SNAPSHOT = OFF,
                DELAYED_DURABILITY = DISABLED 
            WITH ROLLBACK IMMEDIATE;
    END


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET QUERY_STORE (QUERY_CAPTURE_MODE = ALL, DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_PLANS_PER_QUERY = 200, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 367), MAX_STORAGE_SIZE_MB = 100) 
            WITH ROLLBACK IMMEDIATE;
    END


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET QUERY_STORE = OFF 
            WITH ROLLBACK IMMEDIATE;
    END


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
        ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
        ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
        ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
        ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
        ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
        ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
        ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
    END


GO
IF fulltextserviceproperty(N'IsFulltextInstalled') = 1
    EXECUTE sp_fulltext_database 'enable';


GO
PRINT N'Creating [dbo].[Comentarios]...';


GO
CREATE TABLE [dbo].[Comentarios] (
    [idComentario]   INT           IDENTITY (1, 1) NOT NULL,
    [idpublicacao]   INT           NOT NULL,
    [idUtilizador]   INT           NOT NULL,
    [comentario]     VARCHAR (250) NOT NULL,
    [estado]         INT           NULL,
    [dataComentario] DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([idComentario] ASC)
);


GO
PRINT N'Creating [dbo].[Contactos]...';


GO
CREATE TABLE [dbo].[Contactos] (
    [id_contacto]   INT           IDENTITY (1, 1) NOT NULL,
    [id_perfilUser] INT           NOT NULL,
    [tlm]           VARCHAR (250) NULL,
    PRIMARY KEY CLUSTERED ([id_contacto] ASC)
);


GO
PRINT N'Creating [dbo].[Grupos]...';


GO
CREATE TABLE [dbo].[Grupos] (
    [idGrupo]      INT           IDENTITY (1, 1) NOT NULL,
    [id_criador]   INT           NOT NULL,
    [nome]         VARCHAR (250) NULL,
    [desc]         VARCHAR (250) NULL,
    [estado]       INT           NULL,
    [data_criacao] TIMESTAMP     NOT NULL,
    PRIMARY KEY CLUSTERED ([idGrupo] ASC)
);


GO
PRINT N'Creating [dbo].[GrupoUtilizadores]...';


GO
CREATE TABLE [dbo].[GrupoUtilizadores] (
    [id_grupo] INT      NOT NULL,
    [id_user]  INT      NOT NULL,
    [estado]   INT      NOT NULL,
    [tipo]     INT      NOT NULL,
    [data]     DATETIME NULL,
    PRIMARY KEY CLUSTERED ([id_grupo] ASC, [id_user] ASC)
);


GO
PRINT N'Creating [dbo].[Mural]...';


GO
CREATE TABLE [dbo].[Mural] (
    [idMural]       INT IDENTITY (1, 1) NOT NULL,
    [id_utilizador] INT NULL,
    [id_grupo]      INT NULL,
    [tipo]          INT NULL,
    PRIMARY KEY CLUSTERED ([idMural] ASC)
);


GO
PRINT N'Creating [dbo].[Perfil_Utilizador]...';


GO
CREATE TABLE [dbo].[Perfil_Utilizador] (
    [id_Perfil] INT           IDENTITY (1, 1) NOT NULL,
    [id_user]   INT           NOT NULL,
    [firstname] VARCHAR (250) NULL,
    [lastname]  VARCHAR (250) NULL,
    [genero]    INT           NULL,
    [dataNasc]  DATETIME      NOT NULL,
    [estado]    INT           NULL,
    [website]   VARCHAR (250) NULL,
    PRIMARY KEY CLUSTERED ([id_Perfil] ASC)
);


GO
PRINT N'Creating [dbo].[Publicacoes]...';


GO
CREATE TABLE [dbo].[Publicacoes] (
    [id_publicacao]    INT           IDENTITY (1, 1) NOT NULL,
    [id_mural]         INT           NOT NULL,
    [id_user]          INT           NOT NULL,
    [desc]             VARCHAR (250) NOT NULL,
    [estado]           INT           NULL,
    [data_publicacoes] TIMESTAMP     NOT NULL,
    PRIMARY KEY CLUSTERED ([id_publicacao] ASC)
);


GO
PRINT N'Creating [dbo].[Utilizadores]...';


GO
CREATE TABLE [dbo].[Utilizadores] (
    [IdUtilizador]      INT           IDENTITY (1, 1) NOT NULL,
    [username]          VARCHAR (250) NULL,
    [email]             VARCHAR (250) NOT NULL,
    [email_confirmacao] VARCHAR (250) NULL,
    [pass]              VARCHAR (250) NOT NULL,
    [data_registo]      TIMESTAMP     NOT NULL,
    [tipo_utilizador]   INT           NULL,
    [status]            INT           NULL,
    PRIMARY KEY CLUSTERED ([IdUtilizador] ASC)
);


GO
PRINT N'Creating unnamed constraint on [dbo].[Grupos]...';


GO
ALTER TABLE [dbo].[Grupos]
    ADD DEFAULT getDate() FOR [data_criacao];


GO
PRINT N'Creating unnamed constraint on [dbo].[Publicacoes]...';


GO
ALTER TABLE [dbo].[Publicacoes]
    ADD DEFAULT getDate() FOR [data_publicacoes];


GO
PRINT N'Creating unnamed constraint on [dbo].[Utilizadores]...';


GO
ALTER TABLE [dbo].[Utilizadores]
    ADD DEFAULT getDate() FOR [data_registo];


GO
PRINT N'Creating unnamed constraint on [dbo].[Utilizadores]...';


GO
ALTER TABLE [dbo].[Utilizadores]
    ADD DEFAULT 1 FOR [tipo_utilizador];


GO
PRINT N'Creating unnamed constraint on [dbo].[Comentarios]...';


GO
ALTER TABLE [dbo].[Comentarios]
    ADD FOREIGN KEY ([idpublicacao]) REFERENCES [dbo].[Publicacoes] ([id_publicacao]);


GO
PRINT N'Creating unnamed constraint on [dbo].[Comentarios]...';


GO
ALTER TABLE [dbo].[Comentarios]
    ADD FOREIGN KEY ([idUtilizador]) REFERENCES [dbo].[Utilizadores] ([IdUtilizador]);


GO
PRINT N'Creating unnamed constraint on [dbo].[Contactos]...';


GO
ALTER TABLE [dbo].[Contactos]
    ADD FOREIGN KEY ([id_perfilUser]) REFERENCES [dbo].[Perfil_Utilizador] ([id_Perfil]);


GO
PRINT N'Creating unnamed constraint on [dbo].[Grupos]...';


GO
ALTER TABLE [dbo].[Grupos]
    ADD FOREIGN KEY ([id_criador]) REFERENCES [dbo].[Utilizadores] ([IdUtilizador]);


GO
PRINT N'Creating unnamed constraint on [dbo].[GrupoUtilizadores]...';


GO
ALTER TABLE [dbo].[GrupoUtilizadores]
    ADD FOREIGN KEY ([id_grupo]) REFERENCES [dbo].[Grupos] ([idGrupo]);


GO
PRINT N'Creating unnamed constraint on [dbo].[GrupoUtilizadores]...';


GO
ALTER TABLE [dbo].[GrupoUtilizadores]
    ADD FOREIGN KEY ([id_user]) REFERENCES [dbo].[Utilizadores] ([IdUtilizador]);


GO
PRINT N'Creating unnamed constraint on [dbo].[Mural]...';


GO
ALTER TABLE [dbo].[Mural]
    ADD FOREIGN KEY ([id_utilizador]) REFERENCES [dbo].[Utilizadores] ([IdUtilizador]);


GO
PRINT N'Creating unnamed constraint on [dbo].[Mural]...';


GO
ALTER TABLE [dbo].[Mural]
    ADD FOREIGN KEY ([id_grupo]) REFERENCES [dbo].[Grupos] ([idGrupo]);


GO
PRINT N'Creating unnamed constraint on [dbo].[Perfil_Utilizador]...';


GO
ALTER TABLE [dbo].[Perfil_Utilizador]
    ADD FOREIGN KEY ([id_user]) REFERENCES [dbo].[Utilizadores] ([IdUtilizador]);


GO
PRINT N'Creating unnamed constraint on [dbo].[Publicacoes]...';


GO
ALTER TABLE [dbo].[Publicacoes]
    ADD FOREIGN KEY ([id_mural]) REFERENCES [dbo].[Mural] ([idMural]);


GO
PRINT N'Creating unnamed constraint on [dbo].[Publicacoes]...';


GO
ALTER TABLE [dbo].[Publicacoes]
    ADD FOREIGN KEY ([id_user]) REFERENCES [dbo].[Utilizadores] ([IdUtilizador]);


GO
-- Refactoring step to update target server with deployed transaction logs

IF OBJECT_ID(N'dbo.__RefactorLog') IS NULL
BEGIN
    CREATE TABLE [dbo].[__RefactorLog] (OperationKey UNIQUEIDENTIFIER NOT NULL PRIMARY KEY)
    EXEC sp_addextendedproperty N'microsoft_database_tools_support', N'refactoring log', N'schema', N'dbo', N'table', N'__RefactorLog'
END
GO
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '00bcce16-167e-4191-9088-8326bd6eeb45')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('00bcce16-167e-4191-9088-8326bd6eeb45')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '7ed6c875-e4df-4130-b3f5-71b0cd225584')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('7ed6c875-e4df-4130-b3f5-71b0cd225584')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '3d92f9d4-4422-4255-aa34-38b3c39bf420')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('3d92f9d4-4422-4255-aa34-38b3c39bf420')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = 'f942d187-9a31-465f-ab2a-9865d5f9c61b')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('f942d187-9a31-465f-ab2a-9865d5f9c61b')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '5fdb6320-9689-4377-a86d-dada07140893')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('5fdb6320-9689-4377-a86d-dada07140893')

GO

GO
DECLARE @VarDecimalSupported AS BIT;

SELECT @VarDecimalSupported = 0;

IF ((ServerProperty(N'EngineEdition') = 3)
    AND (((@@microsoftversion / power(2, 24) = 9)
          AND (@@microsoftversion & 0xffff >= 3024))
         OR ((@@microsoftversion / power(2, 24) = 10)
             AND (@@microsoftversion & 0xffff >= 1600))))
    SELECT @VarDecimalSupported = 1;

IF (@VarDecimalSupported > 0)
    BEGIN
        EXECUTE sp_db_vardecimal_storage_format N'$(DatabaseName)', 'ON';
    END


GO
PRINT N'Update complete.';


GO
