//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnivSocial.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comentarios
    {
        public int idComentario { get; set; }
        public int idpublicacao { get; set; }
        public int idUtilizador { get; set; }
        public string comentario { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<System.DateTime> dataComentario { get; set; }
    
        public virtual Publicacoes Publicacoes { get; set; }
        public virtual Utilizadores Utilizadores { get; set; }
    }
}
