//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnivSocial.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contactos
    {
        public int id_contacto { get; set; }
        public int id_perfilUser { get; set; }
        public string tlm { get; set; }
    
        public virtual Perfil_Utilizador Perfil_Utilizador { get; set; }
    }
}
