//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnivSocial.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grupos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Grupos()
        {
            this.GrupoUtilizadores = new HashSet<GrupoUtilizadores>();
            this.Mural = new HashSet<Mural>();
        }
    
        public int idGrupo { get; set; }
        public int id_criador { get; set; }
        public string nome { get; set; }
        public string desc { get; set; }
        public Nullable<int> estado { get; set; }
        public byte[] data_criacao { get; set; }
    
        public virtual Utilizadores Utilizadores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GrupoUtilizadores> GrupoUtilizadores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mural> Mural { get; set; }
    }
}
