//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnivSocial.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mural
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mural()
        {
            this.Publicacoes = new HashSet<Publicacoes>();
        }
    
        public int idMural { get; set; }
        public Nullable<int> id_utilizador { get; set; }
        public Nullable<int> id_grupo { get; set; }
        public Nullable<int> tipo { get; set; }
    
        public virtual Grupos Grupos { get; set; }
        public virtual Utilizadores Utilizadores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Publicacoes> Publicacoes { get; set; }
    }
}
