//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnivSocial.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Publicacoes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Publicacoes()
        {
            this.Comentarios = new HashSet<Comentarios>();
        }
    
        public int id_publicacao { get; set; }
        public int id_mural { get; set; }
        public int id_user { get; set; }
        public string desc { get; set; }
        public Nullable<int> estado { get; set; }
        public byte[] data_publicacoes { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comentarios> Comentarios { get; set; }
        public virtual Mural Mural { get; set; }
        public virtual Utilizadores Utilizadores { get; set; }
    }
}
