//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnivSocial.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RedeSocialEntities : DbContext
    {
        public RedeSocialEntities()
            : base("name=RedeSocialEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Comentarios> Comentarios { get; set; }
        public virtual DbSet<Contactos> Contactos { get; set; }
        public virtual DbSet<Grupos> Grupos { get; set; }
        public virtual DbSet<GrupoUtilizadores> GrupoUtilizadores { get; set; }
        public virtual DbSet<Mural> Mural { get; set; }
        public virtual DbSet<Perfil_Utilizador> Perfil_Utilizador { get; set; }
        public virtual DbSet<Publicacoes> Publicacoes { get; set; }
        public virtual DbSet<Utilizadores> Utilizadores { get; set; }
    }
}
