/*
Deployment script for RedeSocialBD

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;

PRINT N'Creating [dbo].[Utilizadores]...';


GO
CREATE TABLE [dbo].[Utilizadores] (
    [IdUtilizador]      INT           IDENTITY (1, 1) NOT NULL,
    [username]          VARCHAR (250) NULL,
    [email]             VARCHAR (250) NOT NULL,
    [email_confirmacao] VARCHAR (250) NULL,
    [pass]              VARCHAR (250) NOT NULL,
    [data_registo]      TIMESTAMP     NOT NULL,
    [tipo_utilizador]   INT           NULL,
    [status]            INT           NULL,
    PRIMARY KEY CLUSTERED ([IdUtilizador] ASC)
);


GO
PRINT N'Creating [dbo].[Perfil_Utilizador]...';


GO
CREATE TABLE [dbo].[Perfil_Utilizador] (
    [id_Perfil] INT           IDENTITY (1, 1) NOT NULL,
    [id_user]   INT           NOT NULL,
    [firstname] VARCHAR (250) NULL,
    [lastname]  VARCHAR (250) NULL,
    [genero]    INT           NULL,
    [dataNasc]  DATETIME      NOT NULL,
    [estado]    INT           NULL,
    [website]   VARCHAR (250) NULL,
    PRIMARY KEY CLUSTERED ([id_Perfil] ASC)
);


GO
PRINT N'Creating [dbo].[Contactos]...';


GO
CREATE TABLE [dbo].[Contactos] (
    [id_contacto]   INT           IDENTITY (1, 1) NOT NULL,
    [id_perfilUser] INT           NOT NULL,
    [tlm]           VARCHAR (250) NULL,
    PRIMARY KEY CLUSTERED ([id_contacto] ASC)
);


GO
PRINT N'Creating [dbo].[Grupos]...';


GO
CREATE TABLE [dbo].[Grupos] (
    [idGrupo]      INT           IDENTITY (1, 1) NOT NULL,
    [id_criador]   INT           NOT NULL,
    [nome]         VARCHAR (250) NULL,
    [desc]         VARCHAR (250) NULL,
    [estado]       INT           NULL,
    [data_criacao] TIMESTAMP     NOT NULL,
    PRIMARY KEY CLUSTERED ([idGrupo] ASC)
);


GO
PRINT N'Creating [dbo].[GrupoUtilizadores]...';


GO
CREATE TABLE [dbo].[GrupoUtilizadores] (
    [id_grupo] INT      NOT NULL,
    [id_user]  INT      NOT NULL,
    [estado]   INT      NOT NULL,
    [tipo]     INT      NOT NULL,
    [data]     DATETIME NULL,
    PRIMARY KEY CLUSTERED ([id_grupo] ASC, [id_user] ASC)
);


GO
PRINT N'Creating [dbo].[Publicacoes]...';


GO
CREATE TABLE [dbo].[Publicacoes] (
    [id_publicacao]    INT           IDENTITY (1, 1) NOT NULL,
    [id_mural]         INT           NOT NULL,
    [id_user]          INT           NOT NULL,
    [desc]             VARCHAR (250) NOT NULL,
    [estado]           INT           NULL,
    [data_publicacoes] TIMESTAMP     NOT NULL,
    PRIMARY KEY CLUSTERED ([id_publicacao] ASC)
);


GO
PRINT N'Creating [dbo].[Comentarios]...';


GO
CREATE TABLE [dbo].[Comentarios] (
    [idComentario]   INT           IDENTITY (1, 1) NOT NULL,
    [idpublicacao]   INT           NOT NULL,
    [idUtilizador]   INT           NOT NULL,
    [comentario]     VARCHAR (250) NOT NULL,
    [estado]         INT           NULL,
    [dataComentario] DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([idComentario] ASC)
);


GO
PRINT N'Creating [dbo].[Mural]...';


GO
CREATE TABLE [dbo].[Mural] (
    [idMural]       INT IDENTITY (1, 1) NOT NULL,
    [id_utilizador] INT NULL,
    [id_grupo]      INT NULL,
    [tipo]          INT NULL,
    PRIMARY KEY CLUSTERED ([idMural] ASC)
);


GO
PRINT N'Creating unnamed constraint on [dbo].[Utilizadores]...';


GO
ALTER TABLE [dbo].[Utilizadores]
    ADD DEFAULT getDate() FOR [data_registo];


GO
PRINT N'Creating unnamed constraint on [dbo].[Utilizadores]...';


GO
ALTER TABLE [dbo].[Utilizadores]
    ADD DEFAULT 1 FOR [tipo_utilizador];


GO
PRINT N'Creating unnamed constraint on [dbo].[Grupos]...';


GO
ALTER TABLE [dbo].[Grupos]
    ADD DEFAULT getDate() FOR [data_criacao];


GO
PRINT N'Creating unnamed constraint on [dbo].[Publicacoes]...';


GO
ALTER TABLE [dbo].[Publicacoes]
    ADD DEFAULT getDate() FOR [data_publicacoes];


GO
PRINT N'Creating unnamed constraint on [dbo].[Perfil_Utilizador]...';


GO
ALTER TABLE [dbo].[Perfil_Utilizador]
    ADD FOREIGN KEY ([id_user]) REFERENCES [dbo].[Utilizadores] ([IdUtilizador]);


GO
PRINT N'Creating unnamed constraint on [dbo].[Contactos]...';


GO
ALTER TABLE [dbo].[Contactos]
    ADD FOREIGN KEY ([id_perfilUser]) REFERENCES [dbo].[Perfil_Utilizador] ([id_Perfil]);


GO
PRINT N'Creating unnamed constraint on [dbo].[Grupos]...';


GO
ALTER TABLE [dbo].[Grupos]
    ADD FOREIGN KEY ([id_criador]) REFERENCES [dbo].[Utilizadores] ([IdUtilizador]);


GO
PRINT N'Creating unnamed constraint on [dbo].[GrupoUtilizadores]...';


GO
ALTER TABLE [dbo].[GrupoUtilizadores]
    ADD FOREIGN KEY ([id_grupo]) REFERENCES [dbo].[Grupos] ([idGrupo]);


GO
PRINT N'Creating unnamed constraint on [dbo].[GrupoUtilizadores]...';


GO
ALTER TABLE [dbo].[GrupoUtilizadores]
    ADD FOREIGN KEY ([id_user]) REFERENCES [dbo].[Utilizadores] ([IdUtilizador]);


GO
PRINT N'Creating unnamed constraint on [dbo].[Publicacoes]...';


GO
ALTER TABLE [dbo].[Publicacoes]
    ADD FOREIGN KEY ([id_mural]) REFERENCES [dbo].[Mural] ([idMural]);


GO
PRINT N'Creating unnamed constraint on [dbo].[Publicacoes]...';


GO
ALTER TABLE [dbo].[Publicacoes]
    ADD FOREIGN KEY ([id_user]) REFERENCES [dbo].[Utilizadores] ([IdUtilizador]);


GO
PRINT N'Creating unnamed constraint on [dbo].[Comentarios]...';


GO
ALTER TABLE [dbo].[Comentarios]
    ADD FOREIGN KEY ([idpublicacao]) REFERENCES [dbo].[Publicacoes] ([id_publicacao]);


GO
PRINT N'Creating unnamed constraint on [dbo].[Comentarios]...';


GO
ALTER TABLE [dbo].[Comentarios]
    ADD FOREIGN KEY ([idUtilizador]) REFERENCES [dbo].[Utilizadores] ([IdUtilizador]);


GO
PRINT N'Creating unnamed constraint on [dbo].[Mural]...';


GO
ALTER TABLE [dbo].[Mural]
    ADD FOREIGN KEY ([id_utilizador]) REFERENCES [dbo].[Utilizadores] ([IdUtilizador]);


GO
PRINT N'Creating unnamed constraint on [dbo].[Mural]...';


GO
ALTER TABLE [dbo].[Mural]
    ADD FOREIGN KEY ([id_grupo]) REFERENCES [dbo].[Grupos] ([idGrupo]);
